'use strict';(function(){
const API='/api/bot',tg=window.Telegram&&window.Telegram.WebApp;const S={cards:[],active:0,tab:'home',user:tg&&tg.initDataUnsafe&&tg.initDataUnsafe.user||{first_name:'Пользователь',username:'guest'},init:tg&&tg.initData||''};
const $=id=>document.getElementById(id);const I={u:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="8" r="3.5"/><path d="M5 20v-1.8c0-2.8 2.8-4.8 7-4.8s7 2 7 4.8V20"/></svg>',h:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="m3 11 9-7 9 7v9H3z"/><path d="M9 20v-6h6v6"/></svg>',p:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 5v14M5 12h14"/></svg>'};
const esc=x=>String(x||'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
async function api(a,b){const r=await fetch(API+'?action='+a,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+S.init},body:JSON.stringify(b||{})});try{return await r.json()}catch(e){return {ok:false,error:'Ошибка сервера'}}}
function toast(t){let x=$('crToast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
const pal=[['#0b1017','#344252'],['#07161c','#136277'],['#160d08','#794217'],['#07150e','#17603e'],['#130918','#5c2872'],['#18090d','#742536'],['#07121e','#20578f'],['#171207','#876615'],['#111','#454c55'],['#071616','#1d7771'],['#180d08','#8b3d19'],['#0d0f1b','#3d478d']];
function tex(c,back){const n=Math.max(0,(+(String(c&&c.skin_id||'photo_1').replace(/\D/g,''))||1)-1)%12,p=pal[n],v=document.createElement('canvas');v.width=1200;v.height=758;const x=v.getContext('2d'),g=x.createLinearGradient(0,0,1200,758);g.addColorStop(0,p[0]);g.addColorStop(.5,p[1]);g.addColorStop(1,p[0]);x.fillStyle=g;x.fillRect(0,0,1200,758);x.strokeStyle='rgba(255,255,255,.17)';x.lineWidth=3;x.strokeRect(25,25,1150,708);x.fillStyle='#fff';x.beginPath();x.arc(80,80,31,0,7);x.fill();x.fillStyle='#111';x.font='700 28px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText('C',80,80);x.fillStyle='#fff';x.font='500 64px Arial';x.fillText(back?'COLLECTIBLE':'@'+String(c&&c.card_username||'collector').replace(/^@/,'').slice(0,8),600,410);return v}
function three(el,c,click){const logo='https://www.photo-pick.com/online/fAY2IN3s.link';el.innerHTML='<div class="css-card-stage"><div class="css-card"><div class="css-face css-front"><span class="css-logo"><img src="'+logo+'" onerror="this.style.display=\'none\'"><b>C</b></span><strong>@'+esc(c&&c.card_username||'collector')+'</strong></div><div class="css-face css-back"><span>COLLECTIBLE</span></div></div></div>';const card=el.querySelector('.css-card');let angle=0,drag=false,lastX=0,stop=false,last=performance.now();const host=el;host.onpointerenter=()=>stop=true;host.onpointerleave=()=>{stop=false;drag=false};host.onpointerdown=e=>{drag=true;lastX=e.clientX;host.setPointerCapture?.(e.pointerId)};host.onpointermove=e=>{if(drag){angle+=(e.clientX-lastX)*.7;lastX=e.clientX}};host.onpointerup=()=>drag=false;function loop(t){const dt=Math.min(.05,(t-last)/1000);last=t;if(!stop&&!drag)angle+=dt*18;card.style.transform='rotateY('+angle+'deg) rotateX(-4deg)';requestAnimationFrame(loop)}requestAnimationFrame(loop);if(click)host.onclick=e=>{if(!drag)openCard(c)}}
function shell(){document.body.insertAdjacentHTML('beforeend','<div id="cardRelease"><header><button id="crProfile">'+I.u+'</button></header><main id="crScreen"></main><nav><button id="crHome">'+I.h+'<span>Главная</span></button><button id="crProf">'+I.u+'<span>Профиль</span></button></nav><div id="crSheet"></div><div id="crToast" class="cr-toast"></div></div>')}
function render(){const c=S.cards[S.active],sc=$('crScreen');sc.innerHTML=S.tab==='home'?(c?'<section class="home"><div class="cardbox"><button id="prev">‹</button><div id="card3d"></div><button id="next">›</button></div><div class="dots">'+S.cards.map((x,i)=>'<i class="'+(i===S.active?'on':'')+'" data-i="'+i+'"></i>').join('')+(S.cards.length<3?'<button id="add">'+I.p+'</button>':'')+'</div><p>Коллекционная карточка. Ею можно будет скоро торговать.</p></section>':'<section class="empty"><button id="first">'+I.p+'</button><span>Создать коллекционную карточку</span></section>'):profile();$('crHome').className=S.tab==='home'?'active':'';$('crProf').className=S.tab==='profile'?'active':'';if(c&&S.tab==='home')three($('card3d'),c,true);bind()}
function profile(){return '<section class="profile"><div class="pCard"><div class="avatar">'+(S.user.photo_url?'<img src="'+esc(S.user.photo_url)+'">':I.u)+'</div><h2>'+esc(S.user.first_name||'Пользователь')+'</h2><div class="muted">@'+esc(S.user.username||'guest')+'</div><div class="count"><b>'+S.cards.length+'</b><span>карточки</span></div></div><div class="settings"><div class="label">НАСТРОЙКИ</div><div class="setting">Максимум карточек <small>3</small></div><div class="setting">Торговля <small>Скоро</small></div></div></section>'}
function bind(){$('crHome').onclick=()=>{S.tab='home';render()};$('crProf').onclick=()=>{S.tab='profile';render()};$('crProfile').onclick=()=>{S.tab='profile';render()};$('prev')?.addEventListener('click',()=>{S.active=(S.active-1+S.cards.length)%S.cards.length;render()});$('next')?.addEventListener('click',()=>{S.active=(S.active+1)%S.cards.length;render()});document.querySelectorAll('.dots i').forEach(x=>x.onclick=()=>{S.active=+x.dataset.i;render()});$('add')?.addEventListener('click',()=>editor());$('first')?.addEventListener('click',()=>editor())}
function sheet(html){const x=$('crSheet');x.innerHTML='<div class="panel">'+html+'</div>';x.classList.add('open')}
function close(){ $('crSheet').classList.remove('open') }
function designs(sel){return '<div class="designs">'+Array.from({length:12},(_,i)=>'<button class="design '+(sel==='photo_'+(i+1)?'sel':'')+'" data-d="photo_'+(i+1)+'" style="background:linear-gradient(135deg,'+pal[i][0]+','+pal[i][1]+')"></button>').join('')+'</div>'}
function editor(c){c=c||{skin_id:'photo_1'};sheet('<div class="head"><b>'+(c.id?'Карточка':'Новая карточка')+'</b><button id="close">×</button></div><label>ЮЗЕРНЕЙМ · 1–8 СИМВОЛОВ</label><input id="nick" maxlength="8" value="'+esc(c.card_username||'')+'" placeholder="username"><label>ПАРОЛЬ · 6 ЦИФР</label><input id="pin" inputmode="numeric" maxlength="6" value="'+esc(c.card_password||'')+'" placeholder="••••••"><label>ДИЗАЙН</label>'+designs(c.skin_id||'photo_1')+'<div id="err"></div><button class="save" id="save">'+(c.id?'Сохранить':'Создать карточку')+'</button>');$('close').onclick=close;document.querySelectorAll('.design').forEach(x=>x.onclick=()=>{document.querySelectorAll('.design').forEach(y=>y.classList.remove('sel'));x.classList.add('sel')});$('save').onclick=async()=>{let n=$('nick').value.trim().replace(/^@/,''),p=$('pin').value.replace(/\D/g,'');if(!/^[A-Za-z0-9_]{1,8}$/.test(n))return $('err').textContent='Юзернейм: до 8 символов';if(!/^\d{6}$/.test(p))return $('err').textContent='Пароль: ровно 6 цифр';let body={card_username:n,card_password:p,skin_id:document.querySelector('.design.sel')?.dataset.d||'photo_1'};if(c.id)body.item_id=c.id;let d=await api(c.id?'update_card_settings':'create_card',body);if(!d.ok)return $('err').textContent=d.error||'Ошибка';close();await load();S.active=c.id?Math.max(0,S.cards.findIndex(x=>x.id===c.id)):S.cards.length-1;render()}}
function openCard(c){sheet('<div class="head"><b>Карточка</b><button id="close">×</button></div><div id="focus" style="height:250px"></div><label>ПАРОЛЬ</label><input id="unlock" inputmode="numeric" maxlength="6" placeholder="6 цифр"><div id="err"></div><label>ДИЗАЙНЫ</label>'+designs(c.skin_id||'photo_1'));$('close').onclick=close;three($('focus'),c,false);document.querySelectorAll('.design').forEach(x=>x.onclick=()=>{if($('unlock').value!==String(c.card_password||''))return $('err').textContent='Введите правильный пароль';c.skin_id=x.dataset.d;close();editor(c)})}
async function load(){let d=await api('get_my_cards');S.cards=d.ok?(d.cards||[]):[]}
async function start(){let l=document.createElement('link');l.rel='stylesheet';l.href='/styles/card-release.css';document.head.appendChild(l);shell();await load();render();if(!localStorage.getItem('card_intro_seen')&&!S.cards.length){localStorage.setItem('card_intro_seen','1');setTimeout(editor,350)}}start()
})();